### PR TITLE
issue #292 - discard support

### PR DESCRIPTION
**Pull request by bruto1**
please review, @rmichela

### CODE REVIEW

**Comment by bruto1** [comment]
can anyone else take the time to review this, please?
@scottslewis @OlegDokuka

**Review by scottslewis — COMMENTED** [review]
First, thanks for the pr.   These changes and tests appear fine to me.   

However, I do not wish to be the only approval for this fix since I'm not at all familiar with this part of the reactive-grpc codebase.  I was not involved in the development of reactive-grpc and was recently added as a committer after helping with reactivex 2->3 transition.

**Comment by rmichela** [comment]
@nikolay-pshenichny Can you please take a look?

**Comment by bruto1** [comment]
I don't know first thing about RxJava, @rmichela  - sry :) Would've changed both impls otherwise

**Comment by bruto1** [comment]
@rmichela ?

**Pull request merged**
