### PR TITLE
Feature/android

### PR DESCRIPTION
**Pull request by rmichela**
Addresses #37 

* Split common generator code from common stub code.
* Refactored common stub module to target JDK6.
* Refactored rxgrpc-stub module to target JDK6.
* Added documentation describing various levels of Android support.

### CODE REVIEW

**Comment by rmichela** [comment]
@OlegZhilo Would it be possible for you to test this -SNAPSHOT change before I merge it?

**Comment by OlegZhilo** [comment]
Woah! Will look into it immediately!

**Comment by OlegZhilo** [comment]
class com.salesforce.reactivegrpccommon.ReactiveStreamObserverPublisher on 37 line is using Long.min(...), but this method available from java 8
https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html#min-long-long-

**Comment by rmichela** [comment]
@OlegZhilo Fixed. Try it now.

**Comment by OlegZhilo** [comment]
@rmichela that work perfect.

**Comment by rmichela** [comment]
I will release this PR to maven central soon. I need to fix a strange behavior in #40 first.

**Pull request merged**
