### PR TITLE
Fix java path separator bug on Windows

### PR DESCRIPTION
**Pull request by Zetten**
This is just a port of the equivalent fix from grpc-java: https://github.com/grpc/grpc-java/pull/6054

### CODE REVIEW

**Review by rmichela — APPROVED** [review]

**Comment by Zetten** [comment]
I signed the CLA, but got an error when submitting the form. It claims I've already signed now so I can't go through again. Is there anything else I can/need to do?

**Comment by rmichela** [comment]
Looks good. Just needs a CLA.

**Comment by rmichela** [comment]
Looking into the CLA issue

**Comment by rmichela** [comment]
Released in [1.2.0](https://github.com/salesforce/reactive-grpc/releases/tag/v1.2.0)

**Pull request merged**
