### PR TITLE
Issue #202: Fully upgrade the lib to RxJava3. Generates classes to Rx…

### PR DESCRIPTION
**Pull request by AndreasLarssons**
Full support for RxJava3 and Java 11

### CODE REVIEW

**Comment by AndreasLarssons** [comment]
This PR has some issues mostly regarding changes in TestSubscriber in version 3. TestSubscriber has lost a lot of methods that were previously utilized in tests. Another change is that TestSubscriber does not have initialFusionMode available anymore from my understanding which lead to me having to ignore some of the tests. 

Also this change does not fully utilize all Java11 features and there is a lot of places where a lambda can now be used instead

**Comment by rmichela** [comment]
First, thank you so much for your investment in Reactive-gRPC. RxJava 3 is a big addition! 🎉 

95 files and 8600 lines is a big chunk of code review. I know this is a big ask, but could you split this PR up a bit? For example, can you just submit just the RxJava3 parts first, without the Java 11 conversion? 

Also, reformatting the code to change the whitespace really clutters up the changes. I use checkstyle to ensure consistent code formatting throughout the project. You will need to add that back in and conform to its standard.

Thank you again for your work. I really want to see RxJava3 support merged. 😄

**Comment by AndreasLarssons** [comment]
Yeah I can start with doing that. Have been using this version internally so mostly just wanted it to work for myself at first 😅. 

I'll rewrite the changes to follow the code formatting style

**Comment by AndreasLarssons** [comment]
Closing this PR in favor of a smaller one without Java 11

**Pull request closed without merging**
